version: '3'

services:
  backend:
    container_name: fastify-jest
    restart: always
    build: .
    ports:
      - '5100:5100'
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/fastify-jest
  mongo:
    container_name: mongodb
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    ports:
      - '27018:27017'
